enum ERROR_CODES {
  INTERNAL_ERROR = 'INTERNAL_ERROR', // An error has occurred.
  SERVER_NOT_AVAILABLE = 'SERVER_NOT_AVAILABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  CANT_CREATE_UNI_ERROR = 'CANT_CREATE_UNI_ERROR',
}

export default ERROR_CODES;
